### ISSUE TITLE
Enable github pages

### ISSUE THREAD

**Issue by eltos** [JACoW-org/JsTimer#1]
Enable github pages, so the repository is automatically deployed as static page at https://jacow-org.github.io/JsTimer and can be viewed online. 

- [x] Enable pages in repo settings
- [x] Rename/create index.html

See https://docs.github.com/en/pages for more information.

**Comment by JACoW-org** [comment]
Thank you @eltos for your suggestion! 
I've just enabled GitHub pages and added a README pointing there!
